#include "url_encoder.h"
/// Url Encoder
/// Simple percent encoding utilty compliant with RFC 3986.
/// https://github.com/kurt-nj/url_encoder
//Boost Software License - Version 1.0 - August 17th, 2003
//
//Permission is hereby granted, free of charge, to any person or organization
//obtaining a copy of the software and accompanying documentation covered by
//this license (the "Software") to use, reproduce, display, distribute,
//execute, and transmit the Software, and to prepare derivative works of the
//Software, and to permit third-parties to whom the Software is furnished to
//do so, all subject to the following:
//
//The copyright notices in the Software and this entire statement, including
//the above license grant, this restriction and the following disclaimer,
//must be included in all copies of the Software, in whole or in part, and
//all derivative works of the Software, unless such copies or derivative
//works are solely in the form of machine-executable object code generated by
//a source language processor.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//DEALINGS IN THE SOFTWARE.

namespace http{

namespace url_encoder {

namespace {
// Check if a character is unreserved
// https://tools.ietf.org/html/rfc3986#section-2.3
bool unreserve_char(char c) {
    switch(c) {
    case '0': case '1': case '2': case '3': case '4':
    case '5': case '6': case '7': case '8': case '9':
    case 'a': case 'b': case 'c': case 'd': case 'e':
    case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o':
    case 'p': case 'q': case 'r': case 's': case 't':
    case 'u': case 'v': case 'w': case 'x': case 'y': case 'z':
    case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J':
    case 'K': case 'L': case 'M': case 'N': case 'O':
    case 'P': case 'Q': case 'R': case 'S': case 'T':
    case 'U': case 'V': case 'W': case 'X': case 'Y': case 'Z':
    case '-': case '.': case '_': case '~':
        return true;
    default:
        return false;
    }
}

// Convert hex character integer
int hexc_to_int(char ch)
{
    if (ch >= '0' && ch <= '9') return ch - '0';
    if (ch >= 'A' && ch <= 'F') return ch - 'A' + 10;
    if (ch >= 'a' && ch <= 'f') return ch - 'a' + 10;
    return -1;
}

// Convert integer to single hex character
// Only goes from 0 to 16
char int_to_hexc(int value) {
    static const char to_hex[16] =
        { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F' };
    return (value >= 0 && value < 16) ? to_hex[value] : 0;
}

} // anonymous namespace


/// URL Encode the input text and returns the encoded string
std::string encode(std::string_view input) {
    std::string output;
    output.reserve(input.size());

    for (char c : input) {
        // unreserved characters can be copied straight
        if (unreserve_char(c)) {
            output.push_back(c);
        }
        else {
            unsigned char uc = static_cast<unsigned char>(c);
            int first = uc >> 4;
            int second = uc & 0x0F;
            output.push_back('%');
            output.push_back(int_to_hexc(first));
            output.push_back(int_to_hexc(second));
        }
    }
    return output;
}

/// URL Decode the input text and returns the decoded string
std::string decode(std::string_view input) {
    std::string output;
    output.reserve(input.size());

    for(size_t x=0; x<input.size(); ++x) {
        char next = input[x];
        // if we find our encode char
        if (input[x] == '%' && x+2 < input.size()) {
            auto first = hexc_to_int(input[x+1]);
            auto second = hexc_to_int(input[x+2]);
            // if the next two values can be decoded, convert it and then move two spots
            if (first >= 0 && second >= 0) {
                int val = (first << 4) + second;
                output.push_back(static_cast<char>(val));
                x+=2;
            }
            // otherwise we have to skip this decoding
            else {
                output.push_back(next);
            }
        }
        else {
            output.push_back(next);
        }
    }
    return output;
}

}

}